// <auto-generated />
using System;
using HomeFlow.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeFlow.Migrations
{
    [DbContext(typeof(HomeFlowDbContext))]
    [Migration("20250510180701_RecipeGroceryItemOrderable")]
    partial class RecipeGroceryItemOrderable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("HomeFlow.Features.Core.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<int>("FamilyMemberType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("HomeFlow.Features.Core.Entities.ImageFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImageFiles");
                });

            modelBuilder.Entity("HomeFlow.Features.Core.Entities.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("HomeFlow.Features.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GroceryItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrinted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GroceryItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroceryListId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RecipeGroceryItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceRecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroceryItemId");

                    b.HasIndex("GroceryListId");

                    b.HasIndex("RecipeGroceryItemId");

                    b.HasIndex("SourceRecipeId");

                    b.ToTable("GroceryListItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GroceryStores");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroceryStoreId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroceryStoreId");

                    b.ToTable("GroceryStoreAisles");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisleGroceryItem", b =>
                {
                    b.Property<Guid>("GroceryStoreAisleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroceryItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("GroceryStoreAisleId", "GroceryItemId");

                    b.HasIndex("GroceryItemId");

                    b.ToTable("GroceryStoreAisleGroceryItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.MealPlannerItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("MealPlannerItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CookTimeInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrepTimeInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Servings")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTimeInMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.RecipeGroceryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GroceryItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("MeasurementFraction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroceryItemId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeGroceryItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ForeignId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("HomeFlow.Features.Core.Entities.FamilyMember", b =>
                {
                    b.HasOne("HomeFlow.Features.Core.Entities.ImageFile", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryListItem", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryItem", "GroceryItem")
                        .WithMany()
                        .HasForeignKey("GroceryItemId");

                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryList", "GroceryList")
                        .WithMany("Items")
                        .HasForeignKey("GroceryListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.RecipeGroceryItem", "RecipeGroceryItem")
                        .WithMany()
                        .HasForeignKey("RecipeGroceryItemId");

                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.Recipe", "SourceRecipe")
                        .WithMany()
                        .HasForeignKey("SourceRecipeId");

                    b.Navigation("GroceryItem");

                    b.Navigation("GroceryList");

                    b.Navigation("RecipeGroceryItem");

                    b.Navigation("SourceRecipe");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisle", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryStore", "GroceryStore")
                        .WithMany("GroceryStoreAisles")
                        .HasForeignKey("GroceryStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryStore");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisleGroceryItem", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryItem", "GroceryItem")
                        .WithMany("GroceryStoreAisleGroceryItems")
                        .HasForeignKey("GroceryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisle", "GroceryStoreAisle")
                        .WithMany("GroceryStoreAisleGroceryItems")
                        .HasForeignKey("GroceryStoreAisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryItem");

                    b.Navigation("GroceryStoreAisle");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.MealPlannerItem", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.Recipe", b =>
                {
                    b.HasOne("HomeFlow.Features.Core.Entities.ImageFile", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.RecipeGroceryItem", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.GroceryItem", "GroceryItem")
                        .WithMany()
                        .HasForeignKey("GroceryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.Recipe", "Recipe")
                        .WithMany("RecipeGroceryItems")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroceryItem");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.RecipeStep", b =>
                {
                    b.HasOne("HomeFlow.Features.MealPlanning.Entities.Recipe", "Recipe")
                        .WithMany("RecipeSteps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryItem", b =>
                {
                    b.Navigation("GroceryStoreAisleGroceryItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStore", b =>
                {
                    b.Navigation("GroceryStoreAisles");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.GroceryStoreAisle", b =>
                {
                    b.Navigation("GroceryStoreAisleGroceryItems");
                });

            modelBuilder.Entity("HomeFlow.Features.MealPlanning.Entities.Recipe", b =>
                {
                    b.Navigation("RecipeGroceryItems");

                    b.Navigation("RecipeSteps");
                });
#pragma warning restore 612, 618
        }
    }
}
